### PR TITLE
feat: Add Formstack Connector

### LINKED ISSUE #192: Add Formstack auth connector

### PR DESCRIPTION
**Pull request by Beadko**
## Checklist
- [x] Ran Linter
- [x] Catalog tests passing
- [x] Created PR from non-main branch 

## Catalog variables
No variables.

## Notes
Resolves #192 

### GET 
URL: <localhost:4444/v2/form.json> 
Get all forms in your account
Screenshot 2024-04-19 at 13 07 31

### POST
URL: <localhost:4444/v2/form.json> 
Create a new form in your account
Screenshot 2024-04-19 at 12 58 20

### PUT
URL:<localhost:4444/v2/form/5737097.json>
Update the details of the specified form
Screenshot 2024-04-19 at 13 11 15

### DELETE
URL:<localhost:4444/v2/form/5737097.json>
Delete the specified form
Screenshot 2024-04-19 at 13 12 12

## Pagination
Please add screenshots that show successful pagination using the connector. 
Before pagination, data starts with a form with different ID number
Screenshot 2024-04-19 at 12 51 26
For pagination, selected 10 items per page (minimum) and start with page 2. Form list starts with a different id
Screenshot 2024-04-19 at 13 08 30

### CODE REVIEW

**Review by jlimatampersand — APPROVED** [review]

**Comment by RajatPawar** [comment]
@Beadko can you please add the raw token response to this PR as a comment?

**Comment by laurenzlong** [comment]
@Beadko can you also run `make fix` to lint this?

**Comment by Beadko** [comment]
@RajatPawar I tried requesting the token again but received an error, probably because the trial has expired. Here is the screenshot I originally, it does include user_id. I have amended the code
image

**Comment by RajatPawar** [comment]
Thanks @Beadko, we are ready to merge this, could you please resolve the conflicts (since there is no test file anymore)

**Comment by Beadko** [comment]
rebased

**Review by RajatPawar — APPROVED** [review]

**Pull request merged**
