### PR TITLE
Added TokenMetadataFields and Updated Proxy as true to DocusignDeveloper connector

### PR DESCRIPTION
**Pull request by sanjay-mitrahsoft**
## Token response via script
Token

## Token response via postman
Token_Postman

### CODE REVIEW

**Comment by laurenzlong** [comment]
@sanjay-mitrahsoft can you please add a screenshot of the output from scripts/oauth/token.go so we can see what the raw token looks like?

**Comment by sanjay-mitrahsoft** [comment]
> @sanjay-mitrahsoft can you please add a screenshot of the output from scripts/oauth/token.go so we can see what the raw token looks like?

I have updated the comment with a token response screenshot

**Comment by sanjay-mitrahsoft** [comment]
## Checklist
- [ ] Ran Linter
- [ ] Catalog tests passing

## Notes
No fishy behaviour observed. All the request/responses were parsed correctly.

## Testing
### GET
URL: https://proxy.withampersand.com/restapi/v2.1/accounts/ee1891e0-141f-45e4-85fd-72d564f247b2/users
get docusign integration


### POST
URL: https://proxy.withampersand.com/restapi/v2.1/accounts/ee1891e0-141f-45e4-85fd-72d564f247b2/users
post docusign integration

### PUT
URL: https://proxy.withampersand.com/restapi/v2.1/accounts/ee1891e0-141f-45e4-85fd-72d564f247b2/users/5a365596-ecb1-4e33-8006-5ceca472182d
put docusign integration

### DELETE
URL: https://proxy.withampersand.com/restapi/v2.1/accounts/ee1891e0-141f-45e4-85fd-72d564f247b2/users
delete docusign integration

### INVALID
URL: https://proxy.withampersand.com/restapi/v2.1/accounts/ee1891e0-141f-45e4-85fd-72d564f247b2/users/5a365596-ecb1-4e33-8006-5ceca472182d
invalid request

### PAGINATION
Requeating a paginated list of users:
URL: https://proxy.withampersand.com/restapi/v2.1/accounts/ee1891e0-141f-45e4-85fd-72d564f247b2/users?count=2
p1

Requesting the next page using the next link provided in the previous request.
image

Going to the next and last page:
image

**Review by laurenzlong — APPROVED** [review]
This is great thank you!

**Pull request merged**
